---
# tasks file for kubectl
- name: install kubectl
  get_url:
    url: "{{ kubectl_url }}"
    dest: /usr/bin/kubectl
    mode: "0755"
    validate_certs: "{{ kubectl_validate_certs }}"
  register: kubectl_install_kubectl
  until: kubectl_install_kubectl is succeeded
  retries: 3
